version = 1

[[annotations]]
path = [ "src/lua/src/*.*", "src/lua/src/Makefile" ]
SPDX-FileCopyrightText = "Copyright (C) 1994-2020 Lua.org, PUC-Rio."
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [ "src/dlfcn*.*" ]
SPDX-FileCopyrightText = "Copyright (c) 2007 Ramiro Polla"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "data/fonts/Roboto-Regular.ttf"
SPDX-FileCopyrightText = "Copyright 2011 Google Inc."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [ "*.md", "src/**/*.rc", "docs/**/*.md", "docs/**/*.css", 
         "test/**/*.md", ".clang-format", "**/.clang-format", 
         "data/intro.txt", "data/developers.txt", "cmake/version.txt.in",
         "data/acknowledgements.txt", "src/res/icon.ico", "data/**/*.png",
         "data/**/*.svg", "data/**/*.els", ".github/**/*.*" ]
SPDX-FileCopyrightText = "Copyright (C) Kushview, LLC."
SPDX-License-Identifier = "CC0-1.0"


[[annotations]]
path = [ "**/CMakeLists.txt", "cmake/*.*", ".gitignore", "**/.gitignore", 
         ".gitmodules", ".dockerignore", ".vscode/*.*",
         "**/sol/config.hpp", "test/**/package.json", "Dockerfile*",
         "**/element.desktop.in", "docs/config.ld" ]
SPDX-FileCopyrightText = "Copyright (C) Kushview, LLC."
SPDX-License-Identifier = "GPL-3.0-or-later"
